// Ported from tmux tty-keys.c @ 8f25579c
/*
 * Copyright (c) 2007 Nicholas Marriott <nicholas.marriott@gmail.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
 * IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

//! The three default key tables (`tty-keys.c:76-431`), in source order.

use crate::term::TtyCodeCode;
use rmux_util::key::{KeyCode, KeyFlags, KeyModifiers, SpecialKey as K};

const META: u64 = KeyModifiers::META.0;
const CTRL: u64 = KeyModifiers::CTRL.0;
const SHIFT: u64 = KeyModifiers::SHIFT.0;
const KEYPAD: u64 = KeyFlags::KEYPAD.0;
const CURSOR: u64 = KeyFlags::CURSOR.0;
const IMPLIED_META: u64 = KeyFlags::IMPLIED_META.0;
const M: u64 = META | IMPLIED_META;

/// `tty_default_raw_keys` (`tty-keys.c:81-222`).
pub const RAW_KEYS: &[(&[u8], KeyCode)] = &[
    (b"\x1bO[", KeyCode(0x1b)),
    (b"\x1bOo", KeyCode(K::KP_SLASH | KEYPAD)),
    (b"\x1bOj", KeyCode(K::KP_STAR | KEYPAD)),
    (b"\x1bOm", KeyCode(K::KP_MINUS | KEYPAD)),
    (b"\x1bOw", KeyCode(K::KP_SEVEN | KEYPAD)),
    (b"\x1bOx", KeyCode(K::KP_EIGHT | KEYPAD)),
    (b"\x1bOy", KeyCode(K::KP_NINE | KEYPAD)),
    (b"\x1bOk", KeyCode(K::KP_PLUS | KEYPAD)),
    (b"\x1bOt", KeyCode(K::KP_FOUR | KEYPAD)),
    (b"\x1bOu", KeyCode(K::KP_FIVE | KEYPAD)),
    (b"\x1bOv", KeyCode(K::KP_SIX | KEYPAD)),
    (b"\x1bOq", KeyCode(K::KP_ONE | KEYPAD)),
    (b"\x1bOr", KeyCode(K::KP_TWO | KEYPAD)),
    (b"\x1bOs", KeyCode(K::KP_THREE | KEYPAD)),
    (b"\x1bOM", KeyCode(K::KP_ENTER | KEYPAD)),
    (b"\x1bOp", KeyCode(K::KP_ZERO | KEYPAD)),
    (b"\x1bOn", KeyCode(K::KP_PERIOD | KEYPAD)),
    (b"\x1bOA", KeyCode(K::UP | CURSOR)),
    (b"\x1bOB", KeyCode(K::DOWN | CURSOR)),
    (b"\x1bOC", KeyCode(K::RIGHT | CURSOR)),
    (b"\x1bOD", KeyCode(K::LEFT | CURSOR)),
    (b"\x1b[A", KeyCode(K::UP | CURSOR)),
    (b"\x1b[B", KeyCode(K::DOWN | CURSOR)),
    (b"\x1b[C", KeyCode(K::RIGHT | CURSOR)),
    (b"\x1b[D", KeyCode(K::LEFT | CURSOR)),
    (b"\x1b\x1bOA", KeyCode(K::UP | CURSOR | META)),
    (b"\x1b\x1bOB", KeyCode(K::DOWN | CURSOR | META)),
    (b"\x1b\x1bOC", KeyCode(K::RIGHT | CURSOR | META)),
    (b"\x1b\x1bOD", KeyCode(K::LEFT | CURSOR | META)),
    (b"\x1b\x1b[A", KeyCode(K::UP | CURSOR | META)),
    (b"\x1b\x1b[B", KeyCode(K::DOWN | CURSOR | META)),
    (b"\x1b\x1b[C", KeyCode(K::RIGHT | CURSOR | META)),
    (b"\x1b\x1b[D", KeyCode(K::LEFT | CURSOR | META)),
    (b"\x1bOH", KeyCode(K::HOME)),
    (b"\x1bOF", KeyCode(K::END)),
    (b"\x1b\x1bOH", KeyCode(K::HOME | M)),
    (b"\x1b\x1bOF", KeyCode(K::END | M)),
    (b"\x1b[H", KeyCode(K::HOME)),
    (b"\x1b[F", KeyCode(K::END)),
    (b"\x1b\x1b[H", KeyCode(K::HOME | M)),
    (b"\x1b\x1b[F", KeyCode(K::END | M)),
    (b"\x1bOa", KeyCode(K::UP | CTRL)),
    (b"\x1bOb", KeyCode(K::DOWN | CTRL)),
    (b"\x1bOc", KeyCode(K::RIGHT | CTRL)),
    (b"\x1bOd", KeyCode(K::LEFT | CTRL)),
    (b"\x1b[a", KeyCode(K::UP | SHIFT)),
    (b"\x1b[b", KeyCode(K::DOWN | SHIFT)),
    (b"\x1b[c", KeyCode(K::RIGHT | SHIFT)),
    (b"\x1b[d", KeyCode(K::LEFT | SHIFT)),
    (b"\x1b[11~", KeyCode(K::F1)),
    (b"\x1b[12~", KeyCode(K::F2)),
    (b"\x1b[13~", KeyCode(K::F3)),
    (b"\x1b[14~", KeyCode(K::F4)),
    (b"\x1b[15~", KeyCode(K::F5)),
    (b"\x1b[17~", KeyCode(K::F6)),
    (b"\x1b[18~", KeyCode(K::F7)),
    (b"\x1b[19~", KeyCode(K::F8)),
    (b"\x1b[20~", KeyCode(K::F9)),
    (b"\x1b[21~", KeyCode(K::F10)),
    (b"\x1b[23~", KeyCode(K::F1 | SHIFT)),
    (b"\x1b[24~", KeyCode(K::F2 | SHIFT)),
    (b"\x1b[25~", KeyCode(K::F3 | SHIFT)),
    (b"\x1b[26~", KeyCode(K::F4 | SHIFT)),
    (b"\x1b[28~", KeyCode(K::F5 | SHIFT)),
    (b"\x1b[29~", KeyCode(K::F6 | SHIFT)),
    (b"\x1b[31~", KeyCode(K::F7 | SHIFT)),
    (b"\x1b[32~", KeyCode(K::F8 | SHIFT)),
    (b"\x1b[33~", KeyCode(K::F9 | SHIFT)),
    (b"\x1b[34~", KeyCode(K::F10 | SHIFT)),
    (b"\x1b[23$", KeyCode(K::F11 | SHIFT)),
    (b"\x1b[24$", KeyCode(K::F12 | SHIFT)),
    (b"\x1b[11^", KeyCode(K::F1 | CTRL)),
    (b"\x1b[12^", KeyCode(K::F2 | CTRL)),
    (b"\x1b[13^", KeyCode(K::F3 | CTRL)),
    (b"\x1b[14^", KeyCode(K::F4 | CTRL)),
    (b"\x1b[15^", KeyCode(K::F5 | CTRL)),
    (b"\x1b[17^", KeyCode(K::F6 | CTRL)),
    (b"\x1b[18^", KeyCode(K::F7 | CTRL)),
    (b"\x1b[19^", KeyCode(K::F8 | CTRL)),
    (b"\x1b[20^", KeyCode(K::F9 | CTRL)),
    (b"\x1b[21^", KeyCode(K::F10 | CTRL)),
    (b"\x1b[23^", KeyCode(K::F11 | CTRL)),
    (b"\x1b[24^", KeyCode(K::F12 | CTRL)),
    (b"\x1b[11@", KeyCode(K::F1 | CTRL | SHIFT)),
    (b"\x1b[12@", KeyCode(K::F2 | CTRL | SHIFT)),
    (b"\x1b[13@", KeyCode(K::F3 | CTRL | SHIFT)),
    (b"\x1b[14@", KeyCode(K::F4 | CTRL | SHIFT)),
    (b"\x1b[15@", KeyCode(K::F5 | CTRL | SHIFT)),
    (b"\x1b[17@", KeyCode(K::F6 | CTRL | SHIFT)),
    (b"\x1b[18@", KeyCode(K::F7 | CTRL | SHIFT)),
    (b"\x1b[19@", KeyCode(K::F8 | CTRL | SHIFT)),
    (b"\x1b[20@", KeyCode(K::F9 | CTRL | SHIFT)),
    (b"\x1b[21@", KeyCode(K::F10 | CTRL | SHIFT)),
    (b"\x1b[23@", KeyCode(K::F11 | CTRL | SHIFT)),
    (b"\x1b[24@", KeyCode(K::F12 | CTRL | SHIFT)),
    (b"\x1b[I", KeyCode(K::FOCUS_IN)),
    (b"\x1b[O", KeyCode(K::FOCUS_OUT)),
    (b"\x1b[200~", KeyCode(K::PASTE_START | IMPLIED_META)),
    (b"\x1b[201~", KeyCode(K::PASTE_END | IMPLIED_META)),
    (b"\x1b[1;5Z", KeyCode(0x09 | CTRL | SHIFT)),
    (b"\x1b[?997;1n", KeyCode(K::REPORT_DARK_THEME)),
    (b"\x1b[?997;2n", KeyCode(K::REPORT_LIGHT_THEME)),
];

/// `tty_default_xterm_keys` (`tty-keys.c:229-260`); `_` takes the modifier
/// parameter.
pub const XTERM_KEYS: &[(&[u8], KeyCode)] = &[
    (b"\x1b[1;_P", KeyCode(K::F1)),
    (b"\x1bO1;_P", KeyCode(K::F1)),
    (b"\x1bO_P", KeyCode(K::F1)),
    (b"\x1b[1;_Q", KeyCode(K::F2)),
    (b"\x1bO1;_Q", KeyCode(K::F2)),
    (b"\x1bO_Q", KeyCode(K::F2)),
    (b"\x1b[1;_R", KeyCode(K::F3)),
    (b"\x1bO1;_R", KeyCode(K::F3)),
    (b"\x1bO_R", KeyCode(K::F3)),
    (b"\x1b[1;_S", KeyCode(K::F4)),
    (b"\x1bO1;_S", KeyCode(K::F4)),
    (b"\x1bO_S", KeyCode(K::F4)),
    (b"\x1b[15;_~", KeyCode(K::F5)),
    (b"\x1b[17;_~", KeyCode(K::F6)),
    (b"\x1b[18;_~", KeyCode(K::F7)),
    (b"\x1b[19;_~", KeyCode(K::F8)),
    (b"\x1b[20;_~", KeyCode(K::F9)),
    (b"\x1b[21;_~", KeyCode(K::F10)),
    (b"\x1b[23;_~", KeyCode(K::F11)),
    (b"\x1b[24;_~", KeyCode(K::F12)),
    (b"\x1b[1;_A", KeyCode(K::UP)),
    (b"\x1b[1;_B", KeyCode(K::DOWN)),
    (b"\x1b[1;_C", KeyCode(K::RIGHT)),
    (b"\x1b[1;_D", KeyCode(K::LEFT)),
    (b"\x1b[1;_H", KeyCode(K::HOME)),
    (b"\x1b[1;_F", KeyCode(K::END)),
    (b"\x1b[5;_~", KeyCode(K::PPAGE)),
    (b"\x1b[6;_~", KeyCode(K::NPAGE)),
    (b"\x1b[2;_~", KeyCode(K::IC)),
    (b"\x1b[3;_~", KeyCode(K::DC)),
];

/// `tty_default_xterm_modifiers` (`tty-keys.c:261-272`), indexed by the
/// xterm parameter; only 2 through 9 are used.
pub const XTERM_MODIFIERS: [u64; 10] = [
    0,
    0,
    SHIFT,
    M,
    SHIFT | M,
    CTRL,
    SHIFT | CTRL,
    M | CTRL,
    SHIFT | M | CTRL,
    M,
];

/// `tty_default_code_keys` (`tty-keys.c:283-431`).
pub const CODE_KEYS: &[(TtyCodeCode, KeyCode)] = &[
    (TtyCodeCode::Kf1, KeyCode(K::F1)),
    (TtyCodeCode::Kf2, KeyCode(K::F2)),
    (TtyCodeCode::Kf3, KeyCode(K::F3)),
    (TtyCodeCode::Kf4, KeyCode(K::F4)),
    (TtyCodeCode::Kf5, KeyCode(K::F5)),
    (TtyCodeCode::Kf6, KeyCode(K::F6)),
    (TtyCodeCode::Kf7, KeyCode(K::F7)),
    (TtyCodeCode::Kf8, KeyCode(K::F8)),
    (TtyCodeCode::Kf9, KeyCode(K::F9)),
    (TtyCodeCode::Kf10, KeyCode(K::F10)),
    (TtyCodeCode::Kf11, KeyCode(K::F11)),
    (TtyCodeCode::Kf12, KeyCode(K::F12)),
    (TtyCodeCode::Kf13, KeyCode(K::F1 | SHIFT)),
    (TtyCodeCode::Kf14, KeyCode(K::F2 | SHIFT)),
    (TtyCodeCode::Kf15, KeyCode(K::F3 | SHIFT)),
    (TtyCodeCode::Kf16, KeyCode(K::F4 | SHIFT)),
    (TtyCodeCode::Kf17, KeyCode(K::F5 | SHIFT)),
    (TtyCodeCode::Kf18, KeyCode(K::F6 | SHIFT)),
    (TtyCodeCode::Kf19, KeyCode(K::F7 | SHIFT)),
    (TtyCodeCode::Kf20, KeyCode(K::F8 | SHIFT)),
    (TtyCodeCode::Kf21, KeyCode(K::F9 | SHIFT)),
    (TtyCodeCode::Kf22, KeyCode(K::F10 | SHIFT)),
    (TtyCodeCode::Kf23, KeyCode(K::F11 | SHIFT)),
    (TtyCodeCode::Kf24, KeyCode(K::F12 | SHIFT)),
    (TtyCodeCode::Kf25, KeyCode(K::F1 | CTRL)),
    (TtyCodeCode::Kf26, KeyCode(K::F2 | CTRL)),
    (TtyCodeCode::Kf27, KeyCode(K::F3 | CTRL)),
    (TtyCodeCode::Kf28, KeyCode(K::F4 | CTRL)),
    (TtyCodeCode::Kf29, KeyCode(K::F5 | CTRL)),
    (TtyCodeCode::Kf30, KeyCode(K::F6 | CTRL)),
    (TtyCodeCode::Kf31, KeyCode(K::F7 | CTRL)),
    (TtyCodeCode::Kf32, KeyCode(K::F8 | CTRL)),
    (TtyCodeCode::Kf33, KeyCode(K::F9 | CTRL)),
    (TtyCodeCode::Kf34, KeyCode(K::F10 | CTRL)),
    (TtyCodeCode::Kf35, KeyCode(K::F11 | CTRL)),
    (TtyCodeCode::Kf36, KeyCode(K::F12 | CTRL)),
    (TtyCodeCode::Kf37, KeyCode(K::F1 | SHIFT | CTRL)),
    (TtyCodeCode::Kf38, KeyCode(K::F2 | SHIFT | CTRL)),
    (TtyCodeCode::Kf39, KeyCode(K::F3 | SHIFT | CTRL)),
    (TtyCodeCode::Kf40, KeyCode(K::F4 | SHIFT | CTRL)),
    (TtyCodeCode::Kf41, KeyCode(K::F5 | SHIFT | CTRL)),
    (TtyCodeCode::Kf42, KeyCode(K::F6 | SHIFT | CTRL)),
    (TtyCodeCode::Kf43, KeyCode(K::F7 | SHIFT | CTRL)),
    (TtyCodeCode::Kf44, KeyCode(K::F8 | SHIFT | CTRL)),
    (TtyCodeCode::Kf45, KeyCode(K::F9 | SHIFT | CTRL)),
    (TtyCodeCode::Kf46, KeyCode(K::F10 | SHIFT | CTRL)),
    (TtyCodeCode::Kf47, KeyCode(K::F11 | SHIFT | CTRL)),
    (TtyCodeCode::Kf48, KeyCode(K::F12 | SHIFT | CTRL)),
    (TtyCodeCode::Kf49, KeyCode(K::F1 | M)),
    (TtyCodeCode::Kf50, KeyCode(K::F2 | M)),
    (TtyCodeCode::Kf51, KeyCode(K::F3 | M)),
    (TtyCodeCode::Kf52, KeyCode(K::F4 | M)),
    (TtyCodeCode::Kf53, KeyCode(K::F5 | M)),
    (TtyCodeCode::Kf54, KeyCode(K::F6 | M)),
    (TtyCodeCode::Kf55, KeyCode(K::F7 | M)),
    (TtyCodeCode::Kf56, KeyCode(K::F8 | M)),
    (TtyCodeCode::Kf57, KeyCode(K::F9 | M)),
    (TtyCodeCode::Kf58, KeyCode(K::F10 | M)),
    (TtyCodeCode::Kf59, KeyCode(K::F11 | M)),
    (TtyCodeCode::Kf60, KeyCode(K::F12 | M)),
    (TtyCodeCode::Kf61, KeyCode(K::F1 | M | SHIFT)),
    (TtyCodeCode::Kf62, KeyCode(K::F2 | M | SHIFT)),
    (TtyCodeCode::Kf63, KeyCode(K::F3 | M | SHIFT)),
    (TtyCodeCode::Kich1, KeyCode(K::IC)),
    (TtyCodeCode::Kdch1, KeyCode(K::DC)),
    (TtyCodeCode::Khome, KeyCode(K::HOME)),
    (TtyCodeCode::Kend, KeyCode(K::END)),
    (TtyCodeCode::Knp, KeyCode(K::NPAGE)),
    (TtyCodeCode::Kpp, KeyCode(K::PPAGE)),
    (TtyCodeCode::Kcbt, KeyCode(K::BTAB)),
    (TtyCodeCode::Kcuu1, KeyCode(K::UP | CURSOR)),
    (TtyCodeCode::Kcud1, KeyCode(K::DOWN | CURSOR)),
    (TtyCodeCode::Kcub1, KeyCode(K::LEFT | CURSOR)),
    (TtyCodeCode::Kcuf1, KeyCode(K::RIGHT | CURSOR)),
    (TtyCodeCode::Kdc2, KeyCode(K::DC | SHIFT)),
    (TtyCodeCode::Kdc3, KeyCode(K::DC | M)),
    (TtyCodeCode::Kdc4, KeyCode(K::DC | SHIFT | M)),
    (TtyCodeCode::Kdc5, KeyCode(K::DC | CTRL)),
    (TtyCodeCode::Kdc6, KeyCode(K::DC | SHIFT | CTRL)),
    (TtyCodeCode::Kdc7, KeyCode(K::DC | M | CTRL)),
    (TtyCodeCode::Kind, KeyCode(K::DOWN | SHIFT)),
    (TtyCodeCode::Kdn2, KeyCode(K::DOWN | SHIFT)),
    (TtyCodeCode::Kdn3, KeyCode(K::DOWN | M)),
    (TtyCodeCode::Kdn4, KeyCode(K::DOWN | SHIFT | M)),
    (TtyCodeCode::Kdn5, KeyCode(K::DOWN | CTRL)),
    (TtyCodeCode::Kdn6, KeyCode(K::DOWN | SHIFT | CTRL)),
    (TtyCodeCode::Kdn7, KeyCode(K::DOWN | M | CTRL)),
    (TtyCodeCode::Kend2, KeyCode(K::END | SHIFT)),
    (TtyCodeCode::Kend3, KeyCode(K::END | M)),
    (TtyCodeCode::Kend4, KeyCode(K::END | SHIFT | M)),
    (TtyCodeCode::Kend5, KeyCode(K::END | CTRL)),
    (TtyCodeCode::Kend6, KeyCode(K::END | SHIFT | CTRL)),
    (TtyCodeCode::Kend7, KeyCode(K::END | M | CTRL)),
    (TtyCodeCode::Khom2, KeyCode(K::HOME | SHIFT)),
    (TtyCodeCode::Khom3, KeyCode(K::HOME | M)),
    (TtyCodeCode::Khom4, KeyCode(K::HOME | SHIFT | M)),
    (TtyCodeCode::Khom5, KeyCode(K::HOME | CTRL)),
    (TtyCodeCode::Khom6, KeyCode(K::HOME | SHIFT | CTRL)),
    (TtyCodeCode::Khom7, KeyCode(K::HOME | M | CTRL)),
    (TtyCodeCode::Kic2, KeyCode(K::IC | SHIFT)),
    (TtyCodeCode::Kic3, KeyCode(K::IC | M)),
    (TtyCodeCode::Kic4, KeyCode(K::IC | SHIFT | M)),
    (TtyCodeCode::Kic5, KeyCode(K::IC | CTRL)),
    (TtyCodeCode::Kic6, KeyCode(K::IC | SHIFT | CTRL)),
    (TtyCodeCode::Kic7, KeyCode(K::IC | M | CTRL)),
    (TtyCodeCode::Klft2, KeyCode(K::LEFT | SHIFT)),
    (TtyCodeCode::Klft3, KeyCode(K::LEFT | M)),
    (TtyCodeCode::Klft4, KeyCode(K::LEFT | SHIFT | M)),
    (TtyCodeCode::Klft5, KeyCode(K::LEFT | CTRL)),
    (TtyCodeCode::Klft6, KeyCode(K::LEFT | SHIFT | CTRL)),
    (TtyCodeCode::Klft7, KeyCode(K::LEFT | M | CTRL)),
    (TtyCodeCode::Knxt2, KeyCode(K::NPAGE | SHIFT)),
    (TtyCodeCode::Knxt3, KeyCode(K::NPAGE | M)),
    (TtyCodeCode::Knxt4, KeyCode(K::NPAGE | SHIFT | M)),
    (TtyCodeCode::Knxt5, KeyCode(K::NPAGE | CTRL)),
    (TtyCodeCode::Knxt6, KeyCode(K::NPAGE | SHIFT | CTRL)),
    (TtyCodeCode::Knxt7, KeyCode(K::NPAGE | M | CTRL)),
    (TtyCodeCode::Kprv2, KeyCode(K::PPAGE | SHIFT)),
    (TtyCodeCode::Kprv3, KeyCode(K::PPAGE | M)),
    (TtyCodeCode::Kprv4, KeyCode(K::PPAGE | SHIFT | M)),
    (TtyCodeCode::Kprv5, KeyCode(K::PPAGE | CTRL)),
    (TtyCodeCode::Kprv6, KeyCode(K::PPAGE | SHIFT | CTRL)),
    (TtyCodeCode::Kprv7, KeyCode(K::PPAGE | M | CTRL)),
    (TtyCodeCode::Krit2, KeyCode(K::RIGHT | SHIFT)),
    (TtyCodeCode::Krit3, KeyCode(K::RIGHT | M)),
    (TtyCodeCode::Krit4, KeyCode(K::RIGHT | SHIFT | M)),
    (TtyCodeCode::Krit5, KeyCode(K::RIGHT | CTRL)),
    (TtyCodeCode::Krit6, KeyCode(K::RIGHT | SHIFT | CTRL)),
    (TtyCodeCode::Krit7, KeyCode(K::RIGHT | M | CTRL)),
    (TtyCodeCode::Kri, KeyCode(K::UP | SHIFT)),
    (TtyCodeCode::Kup2, KeyCode(K::UP | SHIFT)),
    (TtyCodeCode::Kup3, KeyCode(K::UP | M)),
    (TtyCodeCode::Kup4, KeyCode(K::UP | SHIFT | M)),
    (TtyCodeCode::Kup5, KeyCode(K::UP | CTRL)),
    (TtyCodeCode::Kup6, KeyCode(K::UP | SHIFT | CTRL)),
    (TtyCodeCode::Kup7, KeyCode(K::UP | M | CTRL)),
];
