[package]
name = "rmux"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
rmux-sys.workspace = true
rmux-util.workspace = true
rmux-emu.workspace = true
rmux-tty.workspace = true
rmux-server.workspace = true

[features]
systemd = ["rmux-server/systemd"]
sixel = ["rmux-server/sixel"]
