#!/usr/bin/env python3
# Ported from tmux key-bindings.c @ 8f25579c
# Copyright (c) 2007 Nicholas Marriott <nicholas.marriott@gmail.com>
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
# IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""Extract pinned C defaults: source.c defaults.rs [--check]."""
import ast
import json
import re
import sys
from pathlib import Path

source = Path(sys.argv[1]).read_text()
macros = {}
for match in re.finditer(r"^#define (DEFAULT_\w+) \\\n((?:.*\\\n)*.*)", source, re.M):
    macros[match[1]] = match[2].replace("\\\n", "")
tokens = re.compile(r'"(?:\\.|[^"\\])*"|DEFAULT_\w+')

def expand(expression):
    return "".join(ast.literal_eval(token) if token.startswith('"') else expand(macros[token])
                   for token in tokens.findall(expression))

array = source.split("static const char *const defaults[] = {", 1)[1].split("\n\t};", 1)[0]
array = re.sub(r"/\*.*?\*/", "", array, flags=re.S)
defaults = []
position = 0
for token in re.finditer(r'"(?:\\.|[^"\\])*"|DEFAULT_\w+|,', array):
    if token[0] == ',':
        defaults.append(expand(array[position:token.start()]))
        position = token.end()
assert len(defaults) == 308, len(defaults)
license_start = source.index("/*\n * Copyright")
license_text = source[license_start:source.index(" */", license_start) + 3]
lines = ["// Ported from tmux key-bindings.c @ 8f25579c", license_text,
         "", "// Generated by generate_defaults.py from pinned C string literals.", ""]
for name, expression in macros.items():
    lines.append(f"pub const {name}: &[u8] = b{json.dumps(expand(expression))};")
lines.extend(["", "pub const DEFAULT_BINDINGS: [&[u8]; 308] = ["])
lines.extend(f"    b{json.dumps(value)}," for value in defaults)
lines.extend(["];", ""])
if len(sys.argv) == 4 and sys.argv[3] == "--check":
    existing = Path(sys.argv[2]).read_text()
    assert license_text in existing, "missing pinned ISC notice"
    literals = re.compile(r'b"(?:\\.|[^"\\])*"')
    expected = [expand(expression) for expression in macros.values()] + defaults
    actual = [ast.literal_eval(token[1:]) for token in literals.findall(existing)]
    assert actual == expected, "generated defaults differ from pinned C literals"
else:
    Path(sys.argv[2]).write_text("\n".join(lines))
