#!/usr/bin/env python3
"""Generate crates/rmux-util/src/utf8/tables.rs from pinned tmux sources.

Reads utf8.c (the 162 default width entries and the 25 whitespace code
points) and utf8-combined.c (the 72 emoji code points that accept a skin
tone modifier) at tmux 8f25579c and emits const Rust arrays. Output is
deterministic: a second run produces byte-identical text.

Usage: gen-utf8-tables.py [SOURCE_DIR] [OUTPUT]
  SOURCE_DIR  directory holding the pinned utf8.c and utf8-combined.c;
              when omitted or `-` the files are read with
              `git show 8f25579c:...` from $TMUX_SRC or $HOME/fun/tmux.
  OUTPUT      defaults to crates/rmux-util/src/utf8/tables.rs next to this
              repository; `-` writes to stdout.
"""

import os
import re
import subprocess
import sys

PIN = "8f25579c"
HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUTPUT = os.path.join(
    HERE, "..", "crates", "rmux-util", "src", "utf8", "tables.rs"
)


def read_source(source_dir, name):
    if source_dir is not None:
        with open(os.path.join(source_dir, name), encoding="utf-8") as fh:
            return fh.read()
    checkout = os.environ.get("TMUX_SRC") or os.path.join(
        os.environ["HOME"], "fun", "tmux"
    )
    return subprocess.run(
        ["git", "-C", checkout, "show", f"{PIN}:{name}"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def between(text, start, end):
    begin = text.index(start) + len(start)
    return text[begin : text.index(end, begin)]


def default_widths(utf8_c):
    body = between(
        utf8_c, "static struct utf8_width_item utf8_default_width_cache[] = {", "};"
    )
    entries = re.findall(r"\{ \.wc = 0x([0-9A-Fa-f]+), \.width = (\d) \}", body)
    return [(int(wc, 16), int(width)) for wc, width in entries]


def whitespace(utf8_c):
    body = between(utf8_c, "utf8_has_whitespace(const struct utf8_data *ud)", "return (1);")
    body = body[body.index("switch (wc) {") :]
    return [int(wc, 16) for wc in re.findall(r"case 0x([0-9A-Fa-f]+):", body)]


def skin_tone_bases(combined_c):
    body = between(
        combined_c, "/* Emoji skin tone modifiers. */", "if (w >= 0x1F3FB && w <= 0x1F3FF)"
    )
    return [int(wc, 16) for wc in re.findall(r"case 0x([0-9A-Fa-f]+):", body)]


def emit(widths, skin, spaces):
    out = []
    out.append("// Ported from tmux utf8.c, utf8-combined.c @ 8f25579c")
    out.append("// Generated by tools/gen-utf8-tables.py; do not edit by hand.")
    out.append("")
    out.append("/// `utf8_default_width_cache` (utf8.c:53-216): code point and width.")
    out.append("#[rustfmt::skip]")
    out.append(f"pub const DEFAULT_WIDTHS: [(u32, u8); {len(widths)}] = [")
    for wc, width in widths:
        out.append(f"    (0x{wc:05X}, {width}),")
    out.append("];")
    out.append("")
    out.append("/// Code points that combine with a skin tone modifier")
    out.append("/// (utf8-combined.c:124-195).")
    out.append("#[rustfmt::skip]")
    out.append(f"pub const SKIN_TONE_BASES: [u32; {len(skin)}] = [")
    for wc in skin:
        out.append(f"    0x{wc:05X},")
    out.append("];")
    out.append("")
    out.append("/// Unicode whitespace code points tested by `utf8_has_whitespace`")
    out.append("/// (utf8.c:646-670).")
    out.append("#[rustfmt::skip]")
    out.append(f"pub const WHITESPACE: [u32; {len(spaces)}] = [")
    for wc in spaces:
        out.append(f"    0x{wc:04X},")
    out.append("];")
    out.append("")
    return "\n".join(out)


def main(argv):
    source_dir = argv[1] if len(argv) > 1 and argv[1] != "-" else None
    output = argv[2] if len(argv) > 2 else DEFAULT_OUTPUT
    utf8_c = read_source(source_dir, "utf8.c")
    combined_c = read_source(source_dir, "utf8-combined.c")
    text = emit(default_widths(utf8_c), skin_tone_bases(combined_c), whitespace(utf8_c))
    if output == "-":
        sys.stdout.write(text)
    else:
        with open(output, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)


if __name__ == "__main__":
    main(sys.argv)
